service: my-service # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev

functions:
  hello:
    handler: handler.hello
    events:
      - http: GET hello
      - http: POST onrelease